import Head from "next/head";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="h-[100vh] flex flex-col justify-center align-middle text-center">
          <h1 className="text-[72px] bg-clip-text f text-transparent bg-gradient-to-r from-green-400 to-blue-500 font-extrabold">
            Next.js + tailwind + typescript
          </h1>
          <h2 className="max-w-md mx-auto text-2xl">글 바꾸기</h2>
        </div>
      </main>
    </>
  );
};

export default Home;
